In [8]:
import numpy as np
np.random.seed(0)

In [9]:
X = [[1, 2, 3, 2.5], 
    [2.0, 5.0, -1.0, 2.0], 
    [-1.5, 2.7, 3.3, -0.8]]

In [10]:


class layer_Dense:
    def __init__(self, n_inputs, n_neurons): 
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


In [12]:
layer1 = layer_Dense(4, 5)
layer2 = layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)

layer2.forward(layer1.output)
print(layer2.output)

[[-0.37731993 -0.45532983 -0.16581107 -0.09378685 -0.30133249]
 [ 0.12640441  0.58222057  0.74975787 -1.10767981 -0.21231664]
 [-0.29200443 -0.09292818 -0.16745797  0.96540894 -0.18060092]]
[[ 0.07600385  0.04015067]
 [-0.03707247 -0.0575363 ]
 [ 0.04924432  0.02825296]]


In [7]:
inputs = [[1, 2, 3, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]

weights =   [[0.2, 0.8, -0.5, 1], 
            [0.5, -0.91, 0.26, -0.5], 
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 =   [[0.1, -0.14, 0.5], 
            [-0.5, 0.12, -0.33], 
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

layer2_outputs 


array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [6]:
layer_outputs = []

for nueron_weights, neuron_bias in zip(weights, biases): 
    neuron_output = 0
    for n_input, weight in zip(inputs, nueron_weights): 
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

layer_outputs

TypeError: can't multiply sequence by non-int of type 'float'